/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.ClassAluno;
import model.AlunoDAO;
import model.ClassCurso;
import model.CursoDAO;

/**
 *
 * @author Otavio
 */
public class Aluno extends javax.swing.JFrame {

    /**
     * Creates new form Aluno
     */
    public Aluno() throws SQLException {
        initComponents();
        iniciar();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabAluno = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edtMatricula = new javax.swing.JTextField();
        edt_Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edt_RG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edt_CPF = new javax.swing.JTextField();
        cb_Curso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "MATRICULA", "NOME", "RG", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabAlunoMouseClicked(evt);
            }
        });
        TabAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabAlunoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TabAluno);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagem/confirmar.png"))); // NOI18N
        jButton1.setText("Incluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagem/alterar.png"))); // NOI18N
        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagem/excluir.png"))); // NOI18N
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addGap(40, 40, 40)
                .addComponent(jButton3)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        jLabel1.setText("Matricula");

        jLabel2.setText("Nome");

        jLabel3.setText("RG");

        edt_RG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_RGActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        edt_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_CPFActionPerformed(evt);
            }
        });

        cb_Curso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cb_Curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));
        cb_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CursoActionPerformed(evt);
            }
        });

        jLabel5.setText("Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edt_Nome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edt_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_Curso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(edt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void readTable() throws SQLException{
    
        DefaultTableModel modelo = (DefaultTableModel) TabAluno.getModel();
        AlunoDAO cdao = new AlunoDAO();
        modelo.setRowCount(0);
        
        for (ClassAluno c : cdao.read()) {
            
             modelo.addRow(new Object[]{
                c.getCodigo(),
                c.getMatricula(),
                c.getNome(),
                c.getRg(),
                c.getCpf()
             }
             );   
        }
    }
    
    public void refreshCombo() throws SQLException{
        
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) cb_Curso.getModel();
        CursoDAO cursodao = new CursoDAO();
        
        for (model.ClassCurso clscurso : cursodao.read()){ 
            comboBoxModel.addElement(clscurso);    
        }
    }
    
    private void clean(){
        edtMatricula.setText(null);
        edt_CPF.setText(null);
        edt_Nome.setText(null);
        edt_CPF.setText(null);
        edt_RG.setText(null);
    }
    
    private void charge(){
        
        if (TabAluno.getSelectedRow() != -1){
            
            edtMatricula.setText(TabAluno.getValueAt(TabAluno.getSelectedRow(), 1).toString());
            edt_Nome.setText(TabAluno.getValueAt(TabAluno.getSelectedRow(), 2).toString());
            edt_RG.setText(TabAluno.getValueAt(TabAluno.getSelectedRow(), 3).toString());
            edt_CPF.setText(TabAluno.getValueAt(TabAluno.getSelectedRow(), 4).toString());
        }
    }
    
    private void TabAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabAlunoMouseClicked
        // TODO add your handling code here:
        charge();
    }//GEN-LAST:event_TabAlunoMouseClicked

    private void TabAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabAlunoKeyReleased
        // TODO add your handling code here:
        charge();
    }//GEN-LAST:event_TabAlunoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        ClassAluno clsaluno = new ClassAluno();
        AlunoDAO dao = new AlunoDAO();
        clsaluno.setMatricula(edtMatricula.getText());
        clsaluno.setNome(edt_Nome.getText());
        clsaluno.setCpf(edt_CPF.getText());
        clsaluno.setRg(edt_RG.getText());
        
        ClassCurso curso = (ClassCurso) cb_Curso.getSelectedItem();
        
        int idCurso = curso.getCodigo();
        
        clsaluno.setCurso(idCurso);

        try {
            dao.create(clsaluno);
        } catch (SQLException ex) {
            Logger.getLogger(Curso.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            readTable();
        } catch (SQLException ex) {
            Logger.getLogger(Curso.class.getName()).log(Level.SEVERE, null, ex);
        }

        clean();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (TabAluno.getSelectedRow() != -1){

            ClassAluno clsaluno = new ClassAluno();
            AlunoDAO dao = new AlunoDAO();
            clsaluno.setMatricula(edtMatricula.getText());
            clsaluno.setNome(edt_Nome.getText());
            clsaluno.setRg(edt_RG.getText());
            clsaluno.setCpf(edt_CPF.getText());
            
            ClassCurso curso = (ClassCurso) cb_Curso.getSelectedItem();
        
            int idCurso = curso.getCodigo();

            clsaluno.setCurso(idCurso);

            clsaluno.setCodigo((int) TabAluno.getValueAt(TabAluno.getSelectedRow(), 0));
            try {
                dao.update(clsaluno);
            } catch (SQLException ex) {
                Logger.getLogger(Curso.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                readTable();
            } catch (SQLException ex) {
                Logger.getLogger(Curso.class.getName()).log(Level.SEVERE, null, ex);
            }
            clean();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (TabAluno.getSelectedRow() != -1){

            ClassAluno c = new ClassAluno();
            AlunoDAO dao = new AlunoDAO();
            c.setCodigo((int) TabAluno.getValueAt(TabAluno.getSelectedRow(), 0));
            try {
                dao.delete(c);
            } catch (SQLException ex) {
                Logger.getLogger(Curso.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                readTable();
            } catch (SQLException ex) {
                Logger.getLogger(Curso.class.getName()).log(Level.SEVERE, null, ex);
            }
            clean();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void edt_RGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_RGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_RGActionPerformed

    private void edt_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_CPFActionPerformed

    private void cb_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Aluno().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Aluno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabAluno;
    private javax.swing.JComboBox<String> cb_Curso;
    private javax.swing.JTextField edtMatricula;
    private javax.swing.JTextField edt_CPF;
    private javax.swing.JTextField edt_Nome;
    private javax.swing.JTextField edt_RG;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void iniciar() throws SQLException {
       refreshCombo();
       readTable();
    }
}
